### ISSUE TITLE
read-only prevents manual import

### ISSUE THREAD

**Issue by enter-a-random-username** [txtsd/auricularr#2]
All systemd services run on read-only, and I can't Import anything

**Comment by txtsd** [comment]
Could you describe your setup a little bit? 

Imports work fine for me. My media is in `/data`.

**Comment by enter-a-random-username** [comment]
Storage is a fuse mounted system + ACL. Entry point is set in a subfolder inside home.
Mount point location is more of a historical relict and changing it is pure pain (Jellyfin reimports everything with new UUID/hash)

**Comment by txtsd** [comment]
`systemctl edit sonarr` (or whichever service it is you're changing)

There are instructions in there. Basically you'll have to add

```
[Service]
PrivateUsers=false
ProtectHome=false
```

in the override file.

But move it out of `$HOME` eventually.

**Comment by enter-a-random-username** [comment]
Yeah, I edited only read-only variable and it works. Outside home will delete all modifications to Jellyfin entries. I could mount it to /media as well
